image: rust:latest

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install gcc-mingw-w64-x86-64 -y
          - rustup target add x86_64-pc-windows-gnu
          - cargo build -v --release
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads/futurecommander_x86_64-unknown-linux-gnu" --form files=@"target/release/futurecommander"
          - cargo build -v --target=x86_64-pc-windows-gnu
          - ls -R target
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads/futurecommander_x86_64-pc-windows-gnu" --form files=@"target/x86_64-pc-windows-gnu/debug/futurecommander"
          - cargo test --all -v

