image: rust:latest

pipelines:
  branches:
    release/latest:
      - step:
          name: Run tests
          script:
          - cargo test --all -v
          - parallel:
            - step:
                name: Build & publish futurecommander for Linux x86_64
                script:
                - cargo build -v --release
                - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/release/futurecommander"
            - step:
                name: Build & publish futurecommander.exe for Windows x86_64 with MinGW
                script:
                - apt-get update && apt-get install gcc-mingw-w64-x86-64 -y
                - rustup target add x86_64-pc-windows-gnu
                - cargo build -v --release --target=x86_64-pc-windows-gnu
                - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/x86_64-pc-windows-gnu/release/futurecommander.exe"

  pull-requests:
    '**':
      - step:
          name: Run tests
          script:
            - cargo test --all -v
