name: Latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  docker:
    name: Build & push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fcadeillan/futurecommander:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  check:
    runs-on: ubuntu-latest
    container:
      image: fcadeillan/futurecommander:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run lint
      run: clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --all --verbose
  coverage:
    runs-on: ubuntu-latest
    container:
      image: fcadeillan/futurecommander:latest
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v2
      - name: Generate code coverage
        run: cargo tarpaulin --all --count --out Xml -- --test-threads=1
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true